# Generated by Django 4.2.7 on 2023-11-04 02:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("letterbox", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="secretmessage",
            name="encoder",
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="secretmessage",
            name="subject",
            field=models.CharField(default=None, max_length=225),
            preserve_default=False,
        ),
    ]
