# Generated by Django 4.2.7 on 2023-11-04 02:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("letterbox", "0002_secretmessage_encoder_secretmessage_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="secretmessage",
            name="date_sent",
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="secretmessage",
            name="subject",
            field=models.CharField(max_length=225, null=True),
        ),
    ]
