# Generated by Django 4.2.7 on 2023-11-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("letterbox", "0005_secretmessage_encrypted_text_delete_encodedmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="secretmessage",
            name="attempted_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="secretmessage",
            name="key",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
